####################################### Services
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: monitor-cadvisor-c
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - network-monitor
    restart: always
    # ports:
    #   - "8080:8080"

####################################### Networks
networks:
  network-monitor:
    external: true
