####################################### Services
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: core-cadvisor-c
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - network-core
    # restart: always
    # env_file:
    #   - ./.env
    ports:
      - "8080:8080"

####################################### Networks
networks:
  network-core:
    external: true
