####################################### Services
services:
  service-cadvisor:
    image: ahmettoguz/cadvisor:v0.52.1
    container_name: container-cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      # - /var/lib/docker/:/var/lib/docker:ro
      # - /dev/disk/:/dev/disk:ro
    networks:
      - network-monitor
    restart: ${RESTART_POLICY}
    # ports:
    #   - "8080:8080"

####################################### Networks
networks:
  network-monitor:
    external: true
